[package]
name = "linux-sys"
version = "0.1.0"
authors = ["Elichai Turkel <elichai.turkel@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = {version = "0.51", default-features = false, features = ["which-rustfmt"] }