//! Notice: All the types here are autogenerated at build time per platform.
//! The fact that you see `type Foo = u8` doesn't mean you can just use `u8`.
//! please use the types directly as they can change per target/platform or even linux version.
//!
//! This crate contains bindings to all of linux's UAPI headers. the bindings are autogenerated at build time to match the target.
//! for any cross-compilation problems please report to https://github.com/rust-lang/rust-bindgen
#![allow(dead_code,non_camel_case_types,non_snake_case)]

pub mod errno {
    include!(concat!(env!("OUT_DIR"), "/errno.rs"));
}

pub mod fcntl {
    include!(concat!(env!("OUT_DIR"), "/fcntl.rs"));
}
pub mod fs {
    include!(concat!(env!("OUT_DIR"), "/fs.rs"));
}
pub mod r#in {
    include!(concat!(env!("OUT_DIR"), "/in.rs"));
}
pub mod signal {
    include!(concat!(env!("OUT_DIR"), "/signal.rs"));
}
pub mod socket {
    include!(concat!(env!("OUT_DIR"), "/socket.rs"));
}
pub mod time {
    include!(concat!(env!("OUT_DIR"), "/time.rs"));
}
