//! Notice: All the types here are autogenerated at build time per platform.
//! The fact that you see `type Foo = u8` doesn't mean you can just use `u8`.
//! please use the types directly as they can change per target/platform or even linux version.
//!
//! This crate contains bindings to all of linux's UAPI headers. the bindings are autogenerated at build time to match the target.
//! for any cross-compilation problems please report to https://github.com/rust-lang/rust-bindgen


pub mod fcntl;
pub mod fs;
pub mod time;
pub mod signal;
